# draLLaM Continuous Integration pipeline
# Runs when a Pull Request is merged into the 'main' branch.
#
# Step 'release' requires that a GH_TOKEN repository secret exist in GitHub:
# https://github.com/albertomh/draLLaM/settings/secrets/actions
# the value must be a PAT scoped to read & write pull requests.
#
# (c) 2024 Alberto Morón Hernández
name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  REGISTRY: ghcr.io

jobs:
  pre_commit:
    # proceed only when a PR is closed by a merge
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pre-commit

  # tag and create a release when a 'release-' branch is merged
  release:
    if: ${{ startsWith(github.head_ref, 'release-') }}
    needs:
      - pre_commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "TAG=${GITHUB_HEAD_REF#release-}" >> $GITHUB_ENV
        shell: bash
      - uses: ./.github/actions/tag-and-release
        with:
          tag: ${{ env.TAG }}
